
topdir	= ..
srcdirs	= $(arch)
subdirs	= $(arch)/console #quarks
optimize	= -O2
warnings	= -Wall
cppflags	= -nostdinc -fno-builtin -I$(topdir)/include
cflags	= -no-fpic
targets	= libkern.a

include $(topdir)/Makerules
